Repository climate-tech-handbook/climate-tech-handbook, pull requests merged in 2023-06, with the labels that each got.

#44 Update Pages “career-guide”
  docs/career-guide.md
Labels: netlify-cms/pending_publish

#48 Update Pages “solution-indigenous-peoples-forest-tenure”
  docs/solution-indigenous-peoples-forest-tenure.md
  static/img/indigenous-peoples’-forest-tenure.jpg
Labels: netlify-cms/pending_review

#55 Update Pages “solution-methane-leak-management”
  docs/solution-methane-leak-management.md
  static/img/methane-leak-management.jpg
Labels: netlify-cms/pending_publish

#45 Update Blog “hello-world”
  docs/blog/posts/hello-world.md
Labels: netlify-cms/pending_publish

#53 Update Pages “solution-methane-digesters”
  docs/solution-methane-digesters.md
  static/img/methane-digesters.jpg
Labels: netlify-cms/pending_publish

#96 Update Pages “solution-water-distribution-efficiency”
  docs/img/water-distribution-efficiency.webp
  docs/solution-water-distribution-efficiency.md
Labels: netlify-cms/pending_review

#95 Update Pages “solution-waste-to-energy”
  docs/img/waste-to-energy.jpg
  docs/solution-waste-to-energy.md
Labels: netlify-cms/pending_review

#94 Update Pages “solution-walkable-cities”
  docs/img/walkable-cities.webp
  docs/solution-walkable-cities.md
Labels: netlify-cms/pending_review

#93 Update Pages “solution-utility-scale-solar-photovoltaics”
  docs/img/utility-scale-solar-photovoltaics.jpg
  docs/solution-utility-scale-solar-photovoltaics.md
Labels: netlify-cms/pending_review

#92 Update Pages “solution-utility-scale-energy-storage”
  docs/img/utility-scale-energy-storage.jpg
  docs/solution-utility-scale-energy-storage.md
Labels: netlify-cms/pending_review

#91 Update Pages “solution-tropical-forest-restoration”
  docs/img/tropical-forest-restoration.avif
  docs/solution-tropical-forest-restoration.md
Labels: netlify-cms/pending_review

#90 Update Pages “solution-tree-plantations-on-degraded-land”
  docs/img/tree-plantations-on-degraded-land-.jpg
  docs/solution-tree-plantations-on-degraded-land.md
Labels: netlify-cms/pending_review

#89 Update Pages “solution-tree-intercropping”
  docs/img/tree-intercropping.jpg
  docs/solution-tree-intercropping.md
Labels: netlify-cms/pending_review

#88 Update Pages “solution-temperate-forest-restoration”
  docs/img/temperate-forest-restoration.webp
  docs/solution-temperate-forest-restoration.md
Labels: netlify-cms/pending_review

#87 Update Pages “solution-telepresence”
  docs/img/telepresence.png
  docs/solution-telepresence.md
Labels: netlify-cms/pending_review

#86 Update Pages “solution-system-of-rice-intensification”
  docs/img/system-of-rice-intensification.jpg
  docs/solution-system-of-rice-intensification.md
Labels: netlify-cms/pending_review

#85 Update Pages “solution-sustainable-intensification-for-smallholders”
  docs/img/sustainable-intensification-for-smallholders.jpg
  docs/solution-sustainable-intensification-for-smallholders.md
Labels: netlify-cms/pending_review

#84 Update Pages “solution-solar-hot-water”
  docs/img/solar-hot-water.webp
  docs/solution-solar-hot-water.md
Labels: netlify-cms/pending_review

#83 Update Pages “solution-smart-thermostats”
  docs/img/smart-thermostats.webp
  docs/solution-smart-thermostats.md
Labels: netlify-cms/pending_review

#82 Update Pages “solution-small-hydropower”
  docs/img/small-hydropower.png
  docs/solution-small-hydropower.md
Labels: netlify-cms/pending_review

#81 Update Pages “solution-silvopasture”
  docs/img/silvopasture.jpg
  docs/solution-silvopasture.md
Labels: netlify-cms/pending_review

#80 Update Pages “solution-seaweed-farming”
  docs/img/seaweed-farming.jpg
  docs/solution-seaweed-farming.md
Labels: netlify-cms/pending_review

#79 Update Pages “solution-seafloor-protection”
  docs/img/seafloor-protection.jpg
  docs/solution-seafloor-protection.md
Labels: netlify-cms/pending_review

#78 Update Pages “solution-regenerative-annual-cropping”
  docs/img/regenerative-annual-cropping.jpg
  docs/solution-regenerative-annual-cropping.md
Labels: netlify-cms/pending_review

#75 Update Pages “solution-refrigerant-management”
  docs/solution-refrigerant-management.md
  static/img/refrigerant-management.png
Labels: netlify-cms/pending_review

#51 Update Pages “solution-macroalgae-protection-and-restoration”
  docs/solution-macroalgae-protection-and-restoration.md
  static/img/macroalgae-protection-and-restoration.jpg
Labels: netlify-cms/pending_publish

#74 Update Pages “solution-reduced-plastics”
  docs/solution-reduced-plastics.md
  static/img/reduced-plastics.webp
Labels: netlify-cms/pending_review

#73 Update Pages “solution-reduced-food-waste”
  docs/solution-reduced-food-waste.md
  static/img/reduced-food-waste.png
Labels: netlify-cms/pending_review

#72 Update Pages “solution-recycling”
  docs/solution-recycling.md
  static/img/recycling.png
Labels: netlify-cms/pending_review

#71 Update Pages “solution-recycled-plastics”
  docs/solution-recycled-plastics.md
  static/img/recycled-plastics.png
Labels: netlify-cms/pending_review

#70 Update Pages “solution-recycled-paper”
  docs/solution-recycled-paper.md
  static/img/recycled-paper.jpg
Labels: netlify-cms/pending_review

#69 Update Pages “solution-recycled-metals”
  docs/solution-recycled-metals.md
  static/img/recycled-metals.jpg
Labels: netlify-cms/pending_review

#68 Update Pages “solution-public-transit”
  docs/solution-public-transit.md
  static/img/public-transit.webp
Labels: netlify-cms/pending_review

#67 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
  static/img/plant-rich-diets.png
Labels: netlify-cms/pending_review

#66 Update Pages “solution-perennial-staple-crops”
  docs/solution-perennial-staple-crops.md
  static/img/perennial-staple-crops.jpg
Labels: netlify-cms/pending_review

#65 Update Pages “solution-perennial-biomass-production”
  docs/solution-perennial-biomass-production.md
  static/img/perennial-biomass-production.webp
Labels: netlify-cms/pending_review

#64 Update Pages “solution-peatland-protection-and-rewetting”
  docs/solution-peatland-protection-and-rewetting.md
  static/img/peatland-protection-and-rewetting.png
Labels: netlify-cms/pending_review

#63 Update Pages “solution-onshore-wind-turbines”
  docs/solution-onshore-wind-turbines.md
  static/img/onshore-wind-turbines.jpg
Labels: netlify-cms/pending_review

#62 Update Pages “solution-offshore-wind-turbines”
  docs/solution-offshore-wind-turbines.md
  static/img/offshore-wind-turbines.jpg
Labels: netlify-cms/pending_review

#60 Update Pages “solution-nutrient-management”
  docs/solution-nutrient-management.md
  static/img/nutrient-management.webp
Labels: netlify-cms/pending_review

#58 Update Pages “solution-multistrata-agroforestry”
  docs/solution-multistrata-agroforestry.md
  static/img/multistrata-agroforestry.webp
Labels: netlify-cms/pending_review

#57 Update Pages “solution-microgrids”
  docs/solution-microgrids.md
  static/img/microgrids.jpg
Labels: netlify-cms/pending_review

#56 Update Pages “solution-micro-wind-turbines”
  docs/solution-micro-wind-turbines.md
  static/img/micro-wind-turbines.jpg
Labels: netlify-cms/pending_review

#52 Update Pages “solution-managed-grazing”
  docs/solution-managed-grazing.md
  static/img/managed-grazing.png
Labels: netlify-cms/pending_review

#50 Update Pages “solution-low-flow-fixtures”
  docs/solution-low-flow-fixtures.md
  static/img/low-flow-fixtures.png
Labels: netlify-cms/pending_review

#49 Update Pages “solution-led-lighting”
  docs/solution-led-lighting.md
  static/img/led-lighting.jpg
Labels: netlify-cms/pending_review

#20 Update Solutions “solution-multistrata-agroforestry”
  docs/solution-multistrata-agroforestry.md
Labels: netlify-cms/pending_review

#61 Update Pages “solution-ocean-power”
  docs/solution-ocean-power.md
  static/img/ocean-power.png
Labels: netlify-cms/pending_review

#59 Update Pages “solution-nuclear-power”
  docs/solution-nuclear-power.md
  static/img/nuclear-power.webp
Labels: netlify-cms/pending_review

#97 Create Pages “test-image-folder”
  docs/img/hell-yeah-brother-hulk-hogan.gif
  docs/test-image-folder.md
Labels: netlify-cms/pending_publish

#98 Update Pages “test-image-folder”
  docs/test-image-folder.md
Labels: netlify-cms/pending_publish

#99 Update Pages “test-image-folder”
  docs/test-image-folder.md
Labels: netlify-cms/pending_publish

#121 Update Pages “sector-transportation”
  docs/img/transportation.jpeg
  docs/sector-transportation.md
Labels: netlify-cms/pending_review

#120 Update Pages “sector-industry”
  docs/img/industry.jpg
  docs/sector-industry.md
Labels: netlify-cms/pending_review

#116 Update Pages “sector-buildings”
  docs/img/buildings.jpg
  docs/sector-buildings.md
Labels: netlify-cms/pending_review

#115 Update Pages “sector-land-sinks”
  docs/img/land-sinks.jpg
  docs/sector-land-sinks.md
Labels: netlify-cms/pending_review

#125 Update Pages “sector-health-and-education”
  docs/img/healthy-lifestyle.jpg
  docs/sector-health-and-education.md
Labels: netlify-cms/draft

#126 Update Pages “sector-climate-adaptation”
  docs/img/adaptation.jpg
  docs/sector-climate-adaptation.md
Labels: netlify-cms/draft

#127 Update Pages “sector-research-and-education”
  docs/img/education.jpg
  docs/sector-research-and-education.md
Labels: netlify-cms/draft

#128 Update Pages “sector-media-and-journalism”
  docs/img/journalism.jpg
  docs/sector-media-and-journalism.md
Labels: netlify-cms/draft

#129 Update Pages “sector-advocacy-or-policy”
  docs/img/advocacy-and-policy.jpg
  docs/sector-advocacy-or-policy.md
Labels: netlify-cms/draft

#130 Update Pages “sector-climate-adaptation”
  docs/sector-climate-adaptation.md
Labels: netlify-cms/pending_publish

#131 Update Pages “sector-engineered-sinks”
  docs/sector-engineered-sinks.md
Labels: netlify-cms/pending_publish

#132 Update Pages “sector-health-and-education”
  docs/sector-health-and-education.md
Labels: netlify-cms/pending_publish

#133 Update Pages “sector-research-and-education”
  docs/sector-research-and-education.md
Labels: netlify-cms/pending_publish

#134 Update Pages “sector-climate-adaptation”
  docs/sector-climate-adaptation.md
Labels: netlify-cms/pending_publish

#163 Update Pages “career-guide”
  docs/career-guide.md
Labels: netlify-cms/pending_publish

#164 Update Pages “style-guide”
  docs/style-guide.md
Labels: netlify-cms/pending_publish

#170 Update Pages “glossary”
  docs/glossary.md
Labels: netlify-cms/pending_publish

#171 Update Pages “glossary”
  docs/glossary.md
Labels: netlify-cms/pending_publish

#174 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#175 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#176 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#177 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#178 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#180 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#181 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_publish

#182 Update Pages “afresh”
  docs/afresh.md
Labels: netlify-cms/pending_publish

#188 Update Pages “sector-climate-adaptation”
  docs/sector-climate-adaptation.md
Labels: netlify-cms/pending_publish

#187 Update Pages “solution-plant-rich-diets”
  docs/solution-plant-rich-diets.md
Labels: netlify-cms/pending_review

#185 Create Pages “sandbox-1”
  docs/sandbox-1.md
Labels: netlify-cms/pending_publish

#190 Create Pages “companies”
  docs/companies.md
Labels: netlify-cms/pending_publish

#191 Update Pages “companies”
  docs/companies.md
Labels: netlify-cms/pending_publish

#193 Create Pages “climate-adaptation-new-york-city”
  docs/climate-adaptation-new-york-city.md
Labels: netlify-cms/pending_publish

#192 Update Pages “sector-climate-adaptation”
  docs/sector-climate-adaptation.md
Labels: netlify-cms/pending_publish

#194 Update Pages “climate-adaptation-new-york-city”
  docs/climate-adaptation-new-york-city.md
  docs/img/climate-adaptation-new-york.jpg
Labels: netlify-cms/pending_publish

#195 Update Pages “solution-alternative-cement”
  docs/solution-alternative-cement.md
Labels: netlify-cms/draft

#196 modified: docs/sector-electricity.md
  docs/sector-electricity.md
Labels: content
