Repository climate-tech-handbook/climate-tech-handbook, pull requests merged in 2023-08, with the labels that each got.

#252 Update Pages “solution-composting”
  docs/solution-composting.md
Labels: netlify-cms/pending_publish

#255 Update Pages “solution-bioplastics”
  docs/solution-bioplastics.md
Labels: netlify-cms/pending_publish

#256 Update Pages “solution-recycled-paper”
  docs/solution-recycled-paper.md
Labels: netlify-cms/pending_publish

#253 Custom Admonition Support
  docusaurus.config.js
  src/theme/Admonition/index.js
  src/theme/Admonition/styles.module.css
Labels: enhancement

#257 Update Pages “solution-reduced-plastics”
  docs/solution-reduced-plastics.md
Labels: netlify-cms/pending_publish

#273 Update Pages “solution-forest-protection”
  docs/solution-forest-protection.md
Labels: netlify-cms/pending_review

#272 Update Pages “solution-farm-irrigation-efficiency”
  docs/solution-farm-irrigation-efficiency.md
Labels: netlify-cms/pending_review

#271 Update Pages “solution-conservation-agriculture”
  docs/solution-conservation-agriculture.md
Labels: netlify-cms/pending_review

#275 Update Pages “solution-improved-aquaculture”
  docs/solution-improved-aquaculture.md
Labels: netlify-cms/pending_review

#274 Update Pages “solution-grassland-protection”
  docs/solution-grassland-protection.md
Labels: netlify-cms/pending_review

#296 Update Pages “solution-clean-cooking”
  docs/solution-clean-cooking.md
Labels: netlify-cms/pending_review

#276 Update Pages “solution-improved-cattle-feed”
  docs/solution-improved-cattle-feed.md
Labels: netlify-cms/pending_review

#277 Update Pages “solution-improved-manure-management”
  docs/solution-improved-manure-management.md
Labels: netlify-cms/pending_review

#279 Update Pages “solution-indigenous-peoples-forest-tenure”
  docs/solution-indigenous-peoples-forest-tenure.md
Labels: netlify-cms/pending_review

#280 Update Pages “solution-nutrient-management”
  docs/solution-nutrient-management.md
Labels: netlify-cms/pending_review

#282 Update Pages “solution-reduced-food-waste”
  docs/solution-reduced-food-waste.md
Labels: netlify-cms/pending_review

#284 Update Pages “solution-seafloor-protection”
  docs/solution-seafloor-protection.md
Labels: netlify-cms/pending_review

#286 Update Pages “solution-system-of-rice-intensification”
  docs/solution-system-of-rice-intensification.md
Labels: netlify-cms/pending_review

#287 Update Pages “solution-alternative-refrigerants”
  docs/solution-alternative-refrigerants.md
Labels: netlify-cms/pending_review

#288 Update Pages “solution-biogas-for-cooking”
  docs/solution-biogas-for-cooking.md
Labels: netlify-cms/pending_review

#285 Update Pages “solution-sustainable-intensification-for-smallholders”
  docs/solution-sustainable-intensification-for-smallholders.md
Labels: netlify-cms/pending_review

#283 Update Pages “solution-regenerative-annual-cropping”
  docs/solution-regenerative-annual-cropping.md
Labels: netlify-cms/pending_review

#281 Update Pages “solution-peatland-protection-and-rewetting”
  docs/solution-peatland-protection-and-rewetting.md
Labels: netlify-cms/pending_review

#278 Update Pages “solution-improved-rice-production”
  docs/solution-improved-rice-production.md
Labels: netlify-cms/pending_review

#303 Update Pages “solution-recycled-metals”
  docs/solution-recycled-metals.md
Labels: netlify-cms/pending_publish

#304 Update Pages “solution-waste-to-energy”
  docs/solution-waste-to-energy.md
Labels: netlify-cms/pending_publish

#333 Update Pages “career-guide”
  docs/career-guide.md
Labels: netlify-cms/pending_publish

#334 Update Pages “career-guide”
  docs/career-guide.md
Labels: netlify-cms/pending_publish
